import {createClient} from 'npm:@supabase/supabase-js@2.95.0';
import catalog from './products.json' with {type:'json'};
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!;
const ORIGIN='https://favid243.github.io',ADMIN='gamerpixelpulse@gmail.com';
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const auth=()=>createClient(URL,ANON,{auth:{persistSession:false,autoRefreshToken:false}});
const headers={'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS','Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin'};
const result=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
function bad(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
function str(v:unknown,max=250,required=true){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))bad('Revisa los campos del formulario');return v.trim();}
function uuid(v:unknown){const s=str(v,36);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))bad('Identificador inválido');return s;}
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function rate(key:string,max:number,seconds:number){const {data,error}=await db.rpc('ah_rate_limit',{p_key:key,p_max:max,p_seconds:seconds});if(error)bad('Servicio temporalmente no disponible',503);if(!data)bad('Demasiados intentos. Espera un momento.',429);}
async function actor(req:Request){const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(token.startsWith('guest.')){const {data,error}=await db.from('ah_guests').select('owner_id,expires_at').eq('token_hash',await hash(token)).maybeSingle();if(error||!data||new Date(data.expires_at).getTime()<Date.now())bad('Tu sesión expiró. Vuelve a entrar.',401);return {id:data.owner_id,role:'guest',name:'Invitado'};}
 const {data:{user},error}=await auth().auth.getUser(token);if(error||!user)bad('Inicia sesión para continuar',401);const {data:p}=await db.from('ah_profiles').select('username').eq('user_id',user.id).maybeSingle();const {data:admin}=await db.from('ah_admins').select('user_id').eq('user_id',user.id).maybeSingle();return {id:user.id,name:p?.username||'Cliente',role:admin&&user.email_confirmed_at&&user.email?.toLowerCase()===ADMIN?'administrator':'user'};}
function mustAdmin(a:{role:string}){if(a.role!=='administrator')bad('No tienes permiso',403);}
function checked<T extends {error:unknown,data:unknown}>(r:T){if(r.error)bad('No se pudo guardar. Intenta nuevamente.',503);return r.data;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers});try{
 if(req.headers.get('Origin')&&req.headers.get('Origin')!==ORIGIN)bad('Origen no permitido',403);
 const path=new globalThis.URL(req.url).pathname.split('/al-horno-api')[1]||'/';
 let b:any={};if(!['GET','HEAD'].includes(req.method)){if(!req.headers.get('Content-Type')?.startsWith('application/json'))bad('Formato inválido',415);const raw=await req.text();if(raw.length>40000)bad('Solicitud demasiado grande',413);try{b=JSON.parse(raw)}catch{bad('Solicitud inválida')}if(!b||typeof b!=='object'||Array.isArray(b))bad('Solicitud inválida');}
 const ip=await hash(req.headers.get('x-forwarded-for')?.split(',')[0]||req.headers.get('cf-connecting-ip')||'unknown');
 if(path==='/guest'&&req.method==='POST'){await rate('guest:'+ip,20,3600);const token='guest.'+crypto.randomUUID()+crypto.randomUUID();const saved=await db.from('ah_guests').insert({token_hash:await hash(token)}).select('owner_id').single();checked(saved);return result({token,user:{id:saved.data!.owner_id,role:'guest',name:'Invitado'}});}
 if(path==='/register'&&req.method==='POST'){await rate('register:'+ip,8,3600);const username=str(b.name,40).toLowerCase(),email=str(b.email,200).toLowerCase(),password=str(b.password,128);if(!/^[a-z0-9_.-]{3,40}$/.test(username)||password.length<8||!email.includes('@'))bad('Usa un nombre de 3–40 caracteres sin espacios y una contraseña de al menos 8 caracteres.');const {error}=await auth().auth.signUp({email,password,options:{data:{username},emailRedirectTo:ORIGIN+'/al-horno/'}});if(error)bad('No se pudo crear la cuenta. Revisa el nombre, correo y contraseña o intenta más tarde.');return result({message:'Revisa tu correo para confirmar la cuenta. Después inicia sesión con tu nombre y contraseña.'});}
 if(path==='/login'&&req.method==='POST'){await rate('login:'+ip,15,900);const name=str(b.name,200).toLowerCase(),password=str(b.password,128);await rate('login-name:'+await hash(name),15,900);const {data:p}=await db.from('ah_profiles').select('email').eq('username',name).maybeSingle();const {data,error}=await auth().auth.signInWithPassword({email:p?.email||'not-found@invalid.example',password});if(error||!data.session)bad('Nombre o contraseña incorrectos, o correo sin confirmar.',401);return result({session:data.session});}
 if(path==='/refresh'&&req.method==='POST'){await rate('refresh:'+ip,100,3600);const {data,error}=await auth().auth.refreshSession({refresh_token:str(b.refreshToken,500)});if(error||!data.session)bad('Inicia sesión nuevamente',401);return result({session:data.session});}
 const a=await actor(req);if(path==='/me'&&req.method==='GET')return result({user:a});
 if(path==='/orders'&&req.method==='GET'){let q=db.from('ah_orders').select('*').order('created_at',{ascending:false}).limit(300);if(a.role!=='administrator')q=q.eq('owner_id',a.id);return result({orders:checked(await q)});}
 if(path==='/orders'&&req.method==='POST'){
  const key=uuid(b.requestKey);const {data:existing}=await db.from('ah_orders').select('*').eq('owner_id',a.id).eq('request_key',key).maybeSingle();if(existing)return result({order:existing});await rate('order:'+a.id,15,3600);
  if(!Array.isArray(b.items)||!b.items.length||b.items.length>50)bad('Revisa el carrito');
  const items=b.items.map((x:any)=>{if(!x||typeof x!=='object')bad('Producto inválido');const p=catalog.find(p=>p.id===x.id);if(!p||!Number.isInteger(x.qty)||x.qty<1||x.qty>99)bad('Producto o cantidad inválidos');if(x.expectedPrice!==p.price)bad('Un precio cambió. Recarga el catálogo.',409);if(!['Original','Grande (por cotizar)'].includes(x.size)||!Array.isArray(x.toppings)||x.toppings.length>5||x.toppings.some((t:string)=>!['Chocolate','Arequipe','Oreo','Fresas','Chispas de chocolate'].includes(t)))bad('Opciones inválidas');return {id:p.id,name:p.name,price:p.price,qty:x.qty,size:x.size,toppings:[...new Set(x.toppings)],note:str(x.note||'',300,false)};});
  if(!['Efectivo','Nequi','WhatsApp'].includes(b.payment))bad('Forma de pago inválida');const sub=items.reduce((n:number,x:any)=>n+x.price*x.qty,0);const payload={items,name:str(b.name,100),phone:str(b.phone,30),address:str(b.address,300),notes:str(b.notes||'',500,false),payment:b.payment,paymentStatus:'pendiente',subtotal:sub,delivery:4500,total:sub+4500,extrasPending:items.some((x:any)=>x.size!=='Original'||x.toppings.length)};
  const created=await db.from('ah_orders').insert({owner_id:a.id,request_key:key,payload}).select('*').single();if(created.error?.code==='23505'){const duplicate=await db.from('ah_orders').select('*').eq('owner_id',a.id).eq('request_key',key).single();return result({order:checked(duplicate)});}return result({order:checked(created)},201);
 }
 if(path.startsWith('/orders/')&&req.method==='PATCH'){mustAdmin(a);const id=uuid(path.split('/')[2]);if(!['recibido','confirmado','preparando','en_camino','entregado','cancelado'].includes(b.status)||!Number.isInteger(b.version))bad('Estado inválido');const changed=await db.from('ah_orders').update({status:b.status,version:b.version+1}).eq('id',id).eq('version',b.version).select('*').maybeSingle();checked(changed);if(!changed.data)bad('El pedido cambió. Actualiza el panel.',409);return result({order:changed.data});}
 if(path==='/threads'&&req.method==='GET'){let q=db.from('ah_threads').select('*').order('created_at',{ascending:false}).limit(200);if(a.role!=='administrator')q=q.eq('owner_id',a.id);return result({threads:checked(await q)});}
 if(path==='/threads'&&req.method==='POST'){await rate('thread:'+a.id,5,3600);const name=str(b.name,100),message=str(b.message,2000);const thread=await db.from('ah_threads').insert({owner_id:a.id,name}).select('*').single();checked(thread);const msg=await db.from('ah_messages').insert({thread_id:thread.data!.id,sender:'cliente',body:message});if(msg.error){await db.from('ah_threads').delete().eq('id',thread.data!.id);bad('No pudimos guardar tu mensaje. Intenta otra vez.',503)}return result({thread:thread.data},201);}
 const match=path.match(/^\/threads\/([a-f0-9-]+)\/messages$/);if(match){const id=uuid(match[1]);const {data:thread,error}=await db.from('ah_threads').select('*').eq('id',id).maybeSingle();if(error)bad('Servicio no disponible',503);if(!thread||(a.role!=='administrator'&&thread.owner_id!==a.id))bad('Conversación no encontrada',404);if(req.method==='GET')return result({messages:checked(await db.from('ah_messages').select('*').eq('thread_id',id).order('created_at').limit(500))});if(req.method==='POST'){await rate('message:'+a.id,60,3600);const saved=await db.from('ah_messages').insert({thread_id:id,sender:a.role==='administrator'?'administrador':'cliente',body:str(b.message,2000)}).select('*').single();return result({message:checked(saved)},201);}}
 return result({error:'Ruta no encontrada'},404);
 }catch(e){const err=e as any;return result({error:err.status?err.message:'Servicio temporalmente no disponible. Intenta nuevamente.'},err.status||500)}});
