import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const source=fs.readFileSync(path.join(root,'source/index.html'),'utf8');
const ctx={}; vm.createContext(ctx); vm.runInContext(source.slice(source.indexOf('const photo='),source.indexOf('const cats='))+';globalThis.catalog=products',ctx);
fs.mkdirSync(path.join(root,'docs'),{recursive:true});
fs.writeFileSync(path.join(root,'docs/products.json'),JSON.stringify(ctx.catalog));
let page=fs.readFileSync(path.join(root,'pages/index.html'),'utf8');
page=page.replaceAll('href="#carrito"','href="./carrito.html"');
page=page.replace('function draw(){let total=0,count=0;',"function draw(){if(!$('items')){$('count').textContent=cart.reduce((sum,x)=>sum+x.qty,0);save();return}let total=0,count=0;");
page=page.replace("$('items').onclick=", "if($('items'))$('items').onclick=");
page=page.replace("$('checkout').onsubmit=", "if($('checkout'))$('checkout').onsubmit=");
page=page.replace("const isCart=hash==='#carrito';", "const isCart=location.pathname.endsWith('/carrito.html');if(hash==='#carrito'&&!isCart){location.replace('./carrito.html');return}");
page=page.replace("$('carrito').hidden=!isCart;", "if($('carrito'))$('carrito').hidden=!isCart;");
const catalog=page.replace(/<section id="carrito"[\s\S]*?<\/section>/,'');
if(catalog.includes('id="carrito"')||catalog.includes('id="checkout"'))throw Error('Cart must not exist in catalog');
const cartPage=page.replaceAll('href="#catalogo"','href="./index.html#catalogo"').replace('<section id="hero" class="hero">','<section id="hero" class="hero" hidden>').replace('<section id="catalogo">','<section id="catalogo" hidden>');
fs.writeFileSync(path.join(root,'docs/index.html'),catalog);
fs.writeFileSync(path.join(root,'docs/carrito.html'),cartPage);
fs.writeFileSync(path.join(root,'docs/.nojekyll'),'');
console.log('GitHub Pages catalog built: '+ctx.catalog.length+' products');
