import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
const root=new URL('../',import.meta.url),code=fs.readFileSync(new URL('dist/server/index.js',root),'utf8');
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const sql=new DatabaseSync(':memory:');for(const name of fs.readdirSync(new URL('drizzle/',root)).filter(x=>x.endsWith('.sql')))sql.exec(fs.readFileSync(new URL('drizzle/'+name,root),'utf8'));
const DB={prepare(query){const prepared=sql.prepare(query);const wrap=args=>({bind(...values){return wrap(values)},async first(){return prepared.get(...args)||null},async all(){return {results:prepared.all(...args)}},async run(){const r=prepared.run(...args);return {meta:{changes:Number(r.changes)}}}});return wrap([])}};
const origin='https://al-horno-postres.jtatianaortiz.chatgpt.site';
const alice={'oai-authenticated-user-id':'alice','oai-authenticated-user-email':'alice@example.test'},bob={'oai-authenticated-user-id':'bob','oai-authenticated-user-email':'bob@example.test'},owner={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'jtatianaortizbernal@gmail.com'};
async function call(path,headers,method='GET',data,env={DB}){const r=await worker.fetch(new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(data?{body:JSON.stringify(data)}:{})}),env);return {status:r.status,body:await r.json()}}
const payload={requestKey:'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',name:'Ana <script>',phone:'3001234567',address:'Calle 1 # 2-3',district:'Centro',notes:'Portería',terms:true,payment:'Efectivo',items:[{id:'b1',qty:2,price:1,options:{size:'grande',toppings:['oreo'],notes:'Aparte'}}],total:1,status:5,ownerId:'bob'};
assert.equal((await call('/api/orders',{})).status,401);
const first=await call('/api/orders',alice,'POST',payload);assert.equal(first.status,201);assert.equal(first.body.order.total,27800);assert.equal(first.body.order.status,0);assert.equal(first.body.order.email,'alice@example.test');assert.equal(first.body.order.awaitingQuote,true);
const again=await call('/api/orders',alice,'POST',payload);assert.equal(again.body.order.id,first.body.order.id);
const second=await call('/api/orders',bob,'POST',payload);assert.notEqual(second.body.order.id,first.body.order.id);
assert.equal((await call('/api/orders',alice)).body.orders.length,1);assert.equal((await call('/api/orders',bob)).body.orders.length,1);assert.equal((await call('/api/orders',owner)).body.orders.length,2);
assert.equal((await call('/api/orders?owner_id=bob',alice)).body.orders[0].id,first.body.order.id);
const update={version:1,status:2,etaText:'20 minutos',adminNote:'Estamos horneando'};
assert.equal((await call('/api/orders/'+first.body.order.id,bob,'PATCH',update)).status,403);
assert.equal((await call('/api/orders/'+first.body.order.id,owner,'PATCH',update)).status,200);
const aliceSecondDevice=await call('/api/orders',{...alice});assert.equal(aliceSecondDevice.body.orders[0].status,2);assert.equal(aliceSecondDevice.body.orders[0].adminNote,'Estamos horneando');
assert.equal((await call('/api/orders/'+first.body.order.id,owner,'PATCH',update)).status,409);
assert.equal((await call('/api/orders',alice,'POST',{...payload,requestKey:crypto.randomUUID(),items:[{id:'b1',qty:-1}]})).status,400);
assert.equal((await call('/api/orders',alice,'POST',{...payload,requestKey:crypto.randomUUID(),terms:false})).status,400);
assert.equal((await call('/api/orders',{...alice,Origin:'https://attacker.test'},'POST',payload)).status,403);
assert.equal((await call('/api/orders',alice,'GET',null,{})).status,503);
const catalog={version:0,customProducts:[],unavailable:['b1']};assert.equal((await call('/api/catalog',alice,'PUT',catalog)).status,403);assert.equal((await call('/api/catalog',owner,'PUT',catalog)).status,200);
assert.equal((await call('/api/orders',alice,'POST',{...payload,requestKey:crypto.randomUUID()})).status,409);
assert.equal((await call('/api/catalog',owner,'PUT',catalog)).status,409);
assert.equal((await call('/api/orders',alice)).body.orders[0].items[0].name,'Brownie tibio');
sql.close();console.log('PASS: SQLite real, dos clientes/dispositivos, aislamiento, panel administrador, estados, precios del servidor, idempotencia, conflictos, catálogo y fallo sin base de datos.');
